import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils";
import { Providers } from "./provider";
import { Toaster } from "@/components/ui/sonner";
import RecoilContextProvider from "./recoil/atoms";
const inter = Inter({ subsets: ["latin"] });


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Tasker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <RecoilContextProvider>
          <Providers>
            {children}
            <Toaster />
          </Providers>
        </RecoilContextProvider>
      </body>
    </html>
  );
}
